package Frame;

import Clases.Bicicleta;
import Clases.Grafica;
import Clases.Lista;
import Clases.Nodo;
import java.awt.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isaac y la clicka
 */
public class FrmCalidad extends javax.swing.JFrame {

    public Lista myList;
    Grafica grafica;
    private DefaultTableModel tModel;
    JScrollPane js;

//    int con = 0;
    public Lista getLista() {
        return myList;
    }

    /**
     * Creates new form FrmCalidad
     */
    public FrmCalidad() {
        initComponents();
        myList = new Lista();
        //js = new JScrollPane(myTable);
        mostrarInterfaz();

        //mostrarTabla();
    }

    public void mostrarInterfaz() {
//        js.setVisible(true);
//        add(js);
        String data[][] = {};
        String col[] = {"Cuadro", "Llantas", "Manubrios", "Asiento", "Cadena", "Día"};
        tModel = new DefaultTableModel(data, col);
        myTable.setModel(tModel);

    }

    public void borrarTabla() {
        for (int i = 0; i < myTable.getRowCount(); i++) {
            tModel.removeRow(i);
            i -= 1;
        }
    }

    public void mostrarTabla() {
//        js.setVisible(true);
//        add(js);
        for (int i = 0; i < myList.length(); i++) {
            tModel.insertRow(i, new Object[]{});
            try {

                tModel.setValueAt(myList.obtenerCalidad(myList.leerNodoEn(i).getbDato().getiCuad()), i, 0);
                tModel.setValueAt(myList.obtenerCalidad(myList.leerNodoEn(i).getbDato().getiLlan()), i, 1);
                tModel.setValueAt(myList.obtenerCalidad(myList.leerNodoEn(i).getbDato().getiMan()), i, 2);
                tModel.setValueAt(myList.obtenerCalidad(myList.leerNodoEn(i).getbDato().getiAsien()), i, 3);
                tModel.setValueAt(myList.obtenerCalidad(myList.leerNodoEn(i).getbDato().getiCad()), i, 4);
                tModel.setValueAt(myList.obtenerDia(myList.leerNodoEn(i).getbDato().getiDia()), i, 5);
                //con++;
                // tModel.setValueAt(, i, i);//valor, row, col
            } catch (Exception ex) {
                Logger.getLogger(FrmCalidad.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cmbLlan = new javax.swing.JComboBox<>();
        cmbMan = new javax.swing.JComboBox<>();
        cmbAsi = new javax.swing.JComboBox<>();
        cmbCad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbCuad = new javax.swing.JComboBox<>();
        btnMostrar = new javax.swing.JButton();
        btnGuar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbFech = new javax.swing.JComboBox<>();
        btnMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnProba = new javax.swing.JButton();
        btnGrafDia = new javax.swing.JButton();
        cmbGraf = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbDia = new javax.swing.JComboBox<>();
        btnGrafSem = new javax.swing.JButton();
        lblProbaSem = new javax.swing.JLabel();
        lblProbaDia = new javax.swing.JLabel();
        lblMedia = new javax.swing.JLabel();
        lblMediaReg = new javax.swing.JLabel();
        lblMediaMalo = new javax.swing.JLabel();
        btnMenu2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable = new javax.swing.JTable();
        btnActTable = new javax.swing.JButton();
        btbBorrar = new javax.swing.JButton();
        btnMenu3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbLlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malo ", "Regular", "Bueno" }));
        cmbLlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLlanActionPerformed(evt);
            }
        });

        cmbMan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malo ", "Regular", "Bueno" }));

        cmbAsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malo ", "Regular", "Bueno" }));

        cmbCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malo ", "Regular", "Bueno" }));

        jLabel1.setText("Cuadro");

        jLabel2.setText("Llanta");

        jLabel3.setText("Manubrio");

        jLabel4.setText("Asiento");

        jLabel5.setText("Cadena");

        cmbCuad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malo ", "Regular", "Bueno" }));

        btnMostrar.setText("Mostrar");
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostraronClick(evt);
            }
        });

        btnGuar.setText("Guardar");
        btnGuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuaronClick(evt);
            }
        });

        jLabel6.setText("Día");

        cmbFech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));
        cmbFech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFechActionPerformed(evt);
            }
        });

        btnMenu.setText("Menú");
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbLlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbAsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMenu)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbFech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuar)
                    .addComponent(btnMostrar)
                    .addComponent(btnMenu))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calidad", jPanel1);

        btnProba.setText("Probabilidad");
        btnProba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProbaMouseClicked(evt);
            }
        });
        btnProba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbaActionPerformed(evt);
            }
        });

        btnGrafDia.setText("Graficar por día");
        btnGrafDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGrafDiaMouseClicked(evt);
            }
        });

        cmbGraf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuadro", "Llantas", "Manubrios", "Asientos", "Cadena" }));

        jLabel7.setText("Atributo: ");

        jLabel8.setText("Día:");

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));

        btnGrafSem.setText("Graficar por semana");
        btnGrafSem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGrafSemMouseClicked(evt);
            }
        });

        btnMenu2.setText("Menú");
        btnMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenu2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cmbGraf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProba))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenu2)
                            .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGrafSem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrafDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblProbaDia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(lblProbaSem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMediaMalo, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(lblMediaReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGraf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrafDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrafSem)
                    .addComponent(btnProba)
                    .addComponent(btnMenu2))
                .addGap(18, 18, 18)
                .addComponent(lblProbaSem, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProbaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMediaReg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMediaMalo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estadísticas", jPanel2);

        myTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(myTable);

        btnActTable.setText("Actualizar");
        btnActTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActTableMouseClicked(evt);
            }
        });
        btnActTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActTableActionPerformed(evt);
            }
        });

        btbBorrar.setText("Borrar");
        btbBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbBorrarMouseClicked(evt);
            }
        });

        btnMenu3.setText("Menú");
        btnMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMenu3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btbBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActTable)
                        .addGap(18, 18, 18))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActTable)
                    .addComponent(btbBorrar)
                    .addComponent(btnMenu3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Almacen", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbLlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLlanActionPerformed

    private void btnMostraronClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostraronClick
        //int iCuad, iLlan, iMan, iAsien, iCad;
        myList.imprimeLista();
    }//GEN-LAST:event_btnMostraronClick

    private void btnGuaronClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuaronClick
        // TODO add your handling code here:
        int iCuad, iLlan, iMan, iAsien, iCad, iFech;

        iCuad = cmbCuad.getSelectedIndex();
        iLlan = cmbLlan.getSelectedIndex();
        iMan = cmbMan.getSelectedIndex();
        iAsien = cmbAsi.getSelectedIndex();
        iCad = cmbCad.getSelectedIndex();
        iFech = cmbFech.getSelectedIndex();
        myList.agregarNodo(new Nodo(new Bicicleta(iCuad, iLlan, iMan, iAsien, iCad, iFech)));
    }//GEN-LAST:event_btnGuaronClick

    private void btnGrafDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrafDiaMouseClicked
        // TODO add your handling code here:

        grafica = new Grafica(myList, cmbGraf.getSelectedIndex(), cmbDia.getSelectedIndex());

    }//GEN-LAST:event_btnGrafDiaMouseClicked

    private void cmbFechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFechActionPerformed

    private void btnGrafSemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrafSemMouseClicked
        // TODO add your handling code here:
        grafica = new Grafica(myList, cmbGraf.getSelectedIndex());
    }//GEN-LAST:event_btnGrafSemMouseClicked

    private void btnActTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActTableMouseClicked
        // TODO add your handling code here:
        borrarTabla();
        mostrarTabla();
    }//GEN-LAST:event_btnActTableMouseClicked

    private void btnActTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActTableActionPerformed

    private void btbBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbBorrarMouseClicked
        // TODO add your handling code here:
        borrarTabla();
    }//GEN-LAST:event_btbBorrarMouseClicked

    private void btnProbaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProbaMouseClicked
        // TODO add your handling code here:
        String sModa = myList.obtenerCalidad(myList.moda(cmbGraf.getSelectedIndex()));
        String sAtri = myList.obtenerAtributo(cmbGraf.getSelectedIndex());
        String sDia = myList.obtenerDia(cmbDia.getSelectedIndex());
        int iAtri = cmbGraf.getSelectedIndex();
        int iDia = cmbDia.getSelectedIndex();

        System.out.println("La moda es " + myList.moda(cmbGraf.getSelectedIndex()));
        lblProbaSem.setText("La moda para " + sAtri + " es: " + sModa);
        sModa = myList.obtenerCalidad(myList.moda(cmbGraf.getSelectedIndex(), cmbDia.getSelectedIndex()));
        lblProbaDia.setText("La moda para " + sAtri + " del día " + sDia + " es " + sModa);
        lblMedia.setText("La media es " + myList.media(iAtri, 2) + " para las condiciones buenas");
        lblMediaReg.setText("La media es " + myList.media(iAtri, 1) + " para las condiciones regular");
        lblMediaMalo.setText("La media es " + myList.media(iAtri, 0) + " para las condiciones malo");
    }//GEN-LAST:event_btnProbaMouseClicked

    private void btnProbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProbaActionPerformed

    private void onClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClick
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_onClick

    private void btnMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCalidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbBorrar;
    private javax.swing.JButton btnActTable;
    private javax.swing.JButton btnGrafDia;
    private javax.swing.JButton btnGrafSem;
    private javax.swing.JButton btnGuar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMenu2;
    private javax.swing.JButton btnMenu3;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnProba;
    private javax.swing.JComboBox<String> cmbAsi;
    private javax.swing.JComboBox<String> cmbCad;
    private javax.swing.JComboBox<String> cmbCuad;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbFech;
    private javax.swing.JComboBox<String> cmbGraf;
    private javax.swing.JComboBox<String> cmbLlan;
    private javax.swing.JComboBox<String> cmbMan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblMedia;
    private javax.swing.JLabel lblMediaMalo;
    private javax.swing.JLabel lblMediaReg;
    private javax.swing.JLabel lblProbaDia;
    private javax.swing.JLabel lblProbaSem;
    private javax.swing.JTable myTable;
    // End of variables declaration//GEN-END:variables
}
